version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test-py37:  &build-and-test-template
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - run:
          name: Install package in test mode
          command: python -m pip install --upgrade pip && python -m pip install ".[test]"
      - run:
          name: Run pylint
          command: python -m pylint src
      - run:
          name: Run utests
          command: python -m pytest tests/utests
  build-and-test-py38:
    <<: *build-and-test-template
    docker:
      - image: cimg/python:3.8
  build-and-test-py39:
    <<: *build-and-test-template
    docker:
      - image: cimg/python:3.9
  build-and-test-py310:
    <<: *build-and-test-template
    docker:
      - image: cimg/python:3.10
  build-and-test-py311:
    <<: *build-and-test-template
    docker:
      - image: cimg/python:3.11
  build-and-test-py312:
    <<: *build-and-test-template
    docker:
      - image: cimg/python:3.12

workflows:
  test:
    jobs:
      - build-and-test-py37
      - build-and-test-py38
      - build-and-test-py39
      - build-and-test-py310
      - build-and-test-py311
      - build-and-test-py312
